apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbilisim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudbilisim  
  template:
    metadata:
      labels:
        app: cloudbilisim
    spec:
      containers:
      - name: cloudbilisim-container
        image: senol1/cloudbilisim:v1.5
        ports:
        - containerPort: 5000
